### ISSUE TITLE
仓库中本地缓存的格式问题

### ISSUE THREAD

**Issue by lizy14** [wong2/beijing_bus#4]
现无法执行（`gdbm.error: Bad magic number`），会不会是依赖项目的版本问题，毕竟已经时隔十个月

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```

```
>>> lines = BeijingBus.get_all_lines()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "beijing_bus/__init__.py", line 13, in get_all_lines
    return BusLine.get_all_lines()
  File "beijing_bus/line.py", line 73, in get_all_lines
    line_ids = cls.get_all_line_ids()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python2.7/dist-packages/dogpile/lock.py", line 154, in __enter__
    return self._enter()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 610, in get_value
    value = self.backend.get(key)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/backends/file.py", line 220, in get
    with self._dbm_file(False) as dbm:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
gdbm.error: Bad magic number
```

```
>>> lines = BeijingBus.get_all_lines()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/justin/beijing_bus/beijing_bus/__init__.py", line 13, in get_all_lines
    return BusLine.get_all_lines()
  File "/home/justin/beijing_bus/beijing_bus/line.py", line 73, in get_all_lines
    line_ids = cls.get_all_line_ids()
  File "/usr/local/lib/python3.4/dist-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/local/lib/python3.4/dist-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python3.4/dist-packages/dogpile/lock.py", line 154, in __enter__
    return self._enter()
  File "/usr/local/lib/python3.4/dist-packages/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/usr/local/lib/python3.4/dist-packages/dogpile/cache/region.py", line 610, in get_value
    value = self.backend.get(key)
  File "/usr/local/lib/python3.4/dist-packages/dogpile/cache/backends/file.py", line 220, in get
    with self._dbm_file(False) as dbm:
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib/python3.4/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: Bad magic number
```

**Comment by wong2** [comment]
这个应该是由于 dbm 文件不是跨平台的；我已经删除了项目中的 offline_data/bus_offline_data.dbm ，请你更新一下代码，然后执行 `python manage.py build_cache` 建立自己的本地缓存

**Comment by lizy14** [comment]
已解决，非常感谢。我觉得该文件可以保留在仓库中，只需在 build_cache 执行时先删除之即可。

**Comment by wong2** [comment]
@lizy14 我觉得提供一个不能跨平台使用的文件带来的困扰更多些
